
CREATE TABLE IF NOT EXISTS car_brands (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS car_models (
  id TEXT PRIMARY KEY,
  brand_id TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS car_generations (
  id TEXT PRIMARY KEY,
  model_id TEXT NOT NULL,
  name TEXT NOT NULL,
  years TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS car_modifications (
  id TEXT PRIMARY KEY,
  generation_id TEXT NOT NULL,
  name TEXT NOT NULL,
  engine TEXT NOT NULL DEFAULT '',
  transmission TEXT NOT NULL DEFAULT '',
  power TEXT NOT NULL DEFAULT '',
  body_type TEXT,
  seats TEXT,
  length_mm TEXT,
  width_mm TEXT,
  height_mm TEXT,
  wheelbase_mm TEXT,
  track_front_mm TEXT,
  track_rear_mm TEXT,
  curb_weight_kg TEXT,
  wheel_size TEXT,
  ground_clearance_mm TEXT,
  trunk_max_l TEXT,
  trunk_min_l TEXT,
  gross_weight_kg TEXT,
  disk_size TEXT,
  clearance_mm TEXT,
  track_front_width_mm TEXT,
  track_rear_width_mm TEXT,
  payload_kg TEXT,
  train_weight_kg TEXT,
  axle_load_kg TEXT,
  loading_height_mm TEXT,
  cargo_compartment_dims TEXT,
  cargo_volume_m3 TEXT,
  bolt_pattern TEXT,
  engine_type TEXT,
  engine_volume_cc TEXT,
  power_rpm TEXT,
  torque_nm TEXT,
  intake_type TEXT,
  cylinder_layout TEXT,
  cylinder_count TEXT,
  compression_ratio TEXT,
  valves_per_cylinder TEXT,
  turbo_type TEXT,
  bore_mm TEXT,
  stroke_mm TEXT,
  engine_model TEXT,
  engine_location TEXT,
  power_kw TEXT,
  torque_rpm TEXT,
  intercooler TEXT,
  engine_code TEXT,
  timing_system TEXT,
  fuel_consumption_method TEXT,
  gear_count TEXT,
  drive_type TEXT,
  turning_diameter_m TEXT,
  fuel_type TEXT,
  max_speed_kmh TEXT,
  acceleration_100 TEXT,
  fuel_tank_l TEXT,
  eco_standard TEXT,
  fuel_city_l TEXT,
  fuel_highway_l TEXT,
  fuel_mixed_l TEXT,
  range_km TEXT,
  co2_g_km TEXT,
  front_brakes TEXT,
  rear_brakes TEXT,
  front_suspension TEXT,
  rear_suspension TEXT,
  doors_count TEXT,
  country_of_origin TEXT,
  vehicle_class TEXT,
  steering_position TEXT,
  safety_rating TEXT,
  safety_rating_name TEXT
);
